# Generated by Django 5.1.1 on 2024-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
