# Generated by Django 5.1.1 on 2024-10-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_sub_category'),
        ('store', '0009_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.sub_category'),
        ),
    ]
