# Generated by Django 5.1.1 on 2024-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_variation_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('package', 'package')], max_length=100),
        ),
    ]
