# Generated by Django 5.1.1 on 2024-10-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_variation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
