# Generated by Django 5.1.1 on 2024-10-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
    ]
