# Generated by Django 5.1.1 on 2024-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
