# Generated by Django 5.1.1 on 2024-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_subcategory'),
        ('store', '0004_remove_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
