# Generated by Django 5.1.1 on 2024-10-21 19:37

import django.db.models.deletion
import mptt.fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='children', 
                to='category.category'
            ),
        ),
    ]
