# Generated by Django 5.1.1 on 2024-10-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
