# Generated by Django 5.1.1 on 2024-10-22 12:51

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_depth_category_numchild_category_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='depth',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.IntegerField(null=True),
        ),
    ]
