# Generated by Django 5.1.1 on 2024-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_rename_depth_category_level_remove_category_numchild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
