# Generated by Django 4.2.16 on 2024-12-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
