# Generated by Django 5.1.1 on 2024-11-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_product_price_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
