# Generated by Django 5.1.1 on 2024-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
