# Generated by Django 4.2.16 on 2024-11-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_checkout_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
